---
title: 'Kim Norland | design:success founder and CEO'
timezone: UTC
email: success@designsuccess.com
description: 'Kim Norland founded and leads the world’s premier innovation agency
design:success. Believing in the simple philosophy that “one CAN
design success”. Inventor of the world’s only patented and certified
innovation process.'
keywords: 'Kim Norland, design:success, Design Success, innovation processes'
og_image: "assets/img/og_image.jpg"
baseurl: 
url: http://designsuccess.com/kimnorland
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
