---
title: 'kim norland'
timezone: UTC
email: success@designsuccess.com
description: Kim Norland
og_image: "assets/img/og_image.jpg"
baseurl: 
url: http://designsuccess.com/kimnorland
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- webpack
sass:
  style: compressed
github:
- metadata
